name: Limpar deploy antigo
on:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Liberando a fila do GitHub Pages"
